# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rk3506b-custom"
BBFILE_PATTERN_rk3506b-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_rk3506b-custom = "10"

LAYERDEPENDS_rk3506b-custom = "core rockchip-updateimg"
LAYERSERIES_COMPAT_rk3506b-custom = "kirkstone"
